### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by drewjohnson5**

### CODE REVIEW

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by charliemitchel — APPROVED** [review]

**Review by charliemitchel — APPROVED** [review]

**Review by smoovhoggdatazz1 — APPROVED** [review]

**Review by nndmt034 — APPROVED** [review]

**Review by wolfgangschneider14 — APPROVED** [review]

**Review by wolfgangschneider14 — APPROVED** [review]
Yes

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Yodag7354 — APPROVED** [review]
drewjohnson5:patch-1

**Review by Yodag7354 — APPROVED** [review]

**Review by Yodag7354 — APPROVED** [review]
drewjohnson5:patch-1

**Review by Yodag7354 — APPROVED** [review]
SECURIT

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Cololandi — APPROVED** [review]

**Review by bosszhit4l69 — APPROVED** [review]

**Pull request closed without merging**
