### PR TITLE
Create blank.yml

### PR DESCRIPTION
**Pull request by Yodag7354**

### CODE REVIEW

**Review by Hbutlercapone — APPROVED** [review]

**Review by Jsn2win — APPROVED** [review]
Approved

**Review by TurboTicker — APPROVED** [review]

**Review by Cololandi — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Review by Cololandi — APPROVED** [review]

**Comment by uhvyuhs77** [comment]
> 

Approved

**Comment by rorysan333** [comment]
Thank you. I’m looking forward to working at this and I’m thankful for this sites comprised knowledge in this and so many fields. Again thanks 
Rory Markham


Sent from the all new AOL app for iOS


On Tuesday, September 21, 2021, 11:50 PM, uhvyuhs77 ***@***.***> wrote:






Approved

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]
Approve Merge #35

**Pull request closed without merging**
